server:
  port: 18001

--- ### 数据源配置
spring.datasource:
  url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:continew_admin_job}?serverTimezone=Asia/Shanghai&useSSL=true&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
  username: ${DB_USER:root}
  password: ${DB_PWD:123456}
  driver-class-name: com.mysql.cj.jdbc.Driver
## Liquibase 配置
spring.liquibase:
  # 是否启用
  enabled: true
  # 配置文件路径
  change-log: classpath:/db/changelog/db.changelog-master.yaml

--- ### Snail Job 服务端配置
snail-job:
  # 服务端通讯端口（默认：17888）
  server-port: 17888
  # 合并日志默认保存天数
  merge-Log-days: 1
  # 合并日志默认的条数
  merge-Log-num: 500
  # 日志保存时间（单位：天）
  log-storage: 180
  # bucket 总数量
  bucket-total: 128
  # Dashboard 任务容错天数
  summary-day: 7
  # 负载均衡周期时间
  load-balance-cycle-time: 10
  # 每批次拉取重试数据的大小
  retry-pull-page-size: 100
  # 重试任务拉取的并行度
  retry-max-pull-parallel: 2

--- ### 日志配置
logging:
  level:
    com.aizuda.snailjob: INFO
  file:
    path: ../logs