spring:
  application:
    name: codestyle-user
  # session
  session:
    store-type: redis
    # 30 days expire
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codestyle_cloud?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: abc123
  # redis
  data:
    redis:
      # 地址
      host: 47.100.198.147
      # 端口（默认 6379）
      port: 7789
      # 密码（未设置密码时请注释掉）
      #    password: ${REDIS_PWD:123456}
      # 数据库索引
      database: ${REDIS_DB:0}
      # 连接超时时间
      timeout: 10s
      # 是否开启 SSL
      ssl:
        enabled: false
      ## Redisson 配置
server:
  port: 8125
  servlet:
    context-path: /api
    # 30 days expire
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: top.codestyle.file.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
    metadata-report-enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: top.codestyle.file.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






