server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meta_info_db?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  application:
    name: codestyle

mybatis-plus:
  global-config:
    db-config:
      # 表名前缀
      table-prefix: tb_
      # id生成策略 数据库自增
      id-type: auto
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elasticsearch:
  config:
    host: http://localhost:9200
    index-name: meta_info

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info  # 暴露refresh等端点
  endpoint:
    refresh:
      enabled: true  # 启用refresh端点

# 同步配置
sync:
  interval: 10000  # 同步间隔，单位毫秒，默认30秒