spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
--- ### 项目配置
project:
  # 名称
  name: CodeStyle Cloud
  profile: ${spring.profiles.active}
continew:
  data-permission:
    enabled: false